USE [SYSPROD_DESENV_SAP]
GO
/****** Object:  StoredProcedure [dbo].[sp_Atualiza_Insere_Cadprod_Progress]    Script Date: 18/05/2018 15:52:02 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/******
*Procedure resposavel pela integracao do produto na criacao.
*Criada em: 14/05/2018 - Por: David Santos - Edesoft e João Souza Bemis
*Alterado em: 18/08/2018 Por: David Santos
******/
ALTER PROCEDURE [dbo].[sp_Atualiza_Insere_Cadprod_Progress] @ID_EMP int, @CODPROD varchar(18)
AS
BEGIN
	BEGIN TRY
	
	--Comando para não retornar quantidade de linhas afetadas
	SET NOCOUNT ON

	-- Variáveis pata verificar status de liberação de integração dos dados da tabela CADPROD para tabela SAPPRODUT do PROGRESS
	DECLARE @vLiberado_integracao_progress bit
	DECLARE @vIntegrado_Progress           bit
	DECLARE @vStatus_Sysprod	           INT
	DECLARE @ReturnMessage				   VARCHAR(MAX)

	SELECT @vLiberado_integracao_progress = LIBERADO_INTEGRACAO_PROGRESS
		  ,@vStatus_Sysprod				  = STATUS_SYSPROD	
		  ,@vIntegrado_Progress			  = INTEGRADO_PROGRESS 
	FROM CADPROD WHERE ID_EMP = @ID_EMP AND CODPROD = @CODPROD

	-- Se vLiberado_integracao_progress = 1 AND @vStatus_Sysprod = 2 liberado integração progress
	-- @vStatus_Sysprod = 1 É PENDENTE
	-- @vStatus_Sysprod = 1 CONCLUIDO LIBERADO
	IF @vLiberado_integracao_progress = 1 AND @vStatus_Sysprod = 2
	BEGIN
		IF @vIntegrado_Progress = 1
		BEGIN
		-- Se vIntegrado_Progress = 1 integrado no progress então atualiza os dados na tabela
			UPDATE PROGRESS_PRODUTOS
			SET  EMPCODEMP        = PROGRESS_DEPARA."EMP-CODEMP"
				,SAPCODEMP        = CADPROD.ID_EMP                                                
				,SAPCODPRO        = CADPROD.CODPROD                                               
				,SAPDESCRI        = CADPROD.DESCPROD                                         
			    ,PRODATCAD        = CADPROD.DATA_CAD_MATER  
				,SAPCODVID		  = CADPROD.COD_VIDA
				,TUNSIGUNI		  = UNIDADES.SIMBOL
			--  				  = CADPROD.ID_UNID_MAQ
				,DIMCODSIF		  = CADPROD.COD_SIF
				,DIMLGCORT        = CADPROD.CP_LARG
				,DIMTLCORT		  = CADPROD.CP_LARG_NOM_MAIOR
				,DIMTLCOR1		  = CADPROD.CP_LARG_NOM_MENOR
				,DIMLGLONG		  = CADPROD.CP_LARG_LONG_NOM
				,DIMLGTRAN		  = CADPROD.CP_LARG_TRANS_NOM
				,DIMDIAINT		  = CADPROD.CP_DIAM_INTERNO
				,DIMDMEXTE		  = CADPROD.CP_DIAM_EXTERNO
				,DIMDENSID		  = CADPROD.CP_DENSIDADE
				,DIMESPESS		  = CADPROD.CP_ESPE
				,DIMESTOT1		  = CADPROD.CP_ESPESSURA_MAIOR
				,DIMESTOT2		  = CADPROD.CP_ESPESSURA_MENOR
				,DIMGRTOTA		  = CADPROD.CP_GRAM_TOTAL
				,DIMTOLGM2		  = CADPROD.CP_GRAM_TOTAL_MIN
				,DIMTOLEGM		  = CADPROD.CP_GRAM_TOTAL_MAX
				,DIMGRMTLI		  = CADPROD.CP_MASSA_ML
				,DIMGRMTL1		  = CADPROD.CP_MASSA_ML_MAIOR
				,DIMGRMTL2		  = CADPROD.CP_MASSA_ML_MENOR
				,DIMREPLAT		  = CADPROD.CP_REPETICOES
				,DIMREPLON		  = CADPROD.CPV_REP_ALT
				,PROSELFSC		  = CADPROD.CP_SELO_FSC
				,PROSEPEFC		  = CADPROD.CP_SELO_PEFC
				,DIMBASPAL		  = CADPROD.CP_VOLUMES_PALLET
				,DIMQTITCX		  = CADPROD.CP_PECAS_VOLUME
				,DIMBOBKGS		  = CADPROD.CP_KILOS_BOBINA
				,DIMMTSBOB		  = CADPROD.CP_METROS_POR_BOBINA
				,DIMCPRSAC		  = CADPROD.CP_SACO_ALT
				,DIMVARALT		  = CADPROD.CP_SACO_ALT_VAR1
				,DIMLGRSAC		  = CADPROD.CP_SACO_LARG
				,DIMVARLGS		  = CADPROD.CP_SACO_LARG_VAR1
				,SAPNVCODFOTO	  = CADPROD.CP_GERA_COD_FOTOMONTAGEM
				,SAPSEQFOTO		  = CADPROD.CP_FOTOMONTAGEM
				,DIMFMVARIMG	  = CADPROD.CP_FOTOM_VAR_LAYOUT
				,SAPNVCODPADCOR	  = CADPROD.CP_GERA_COD_PAD_COR
				,SAPSEQPAD		  = CADPROD.CP_PADRAO_COR
				,DIMPASSFC		  = CADPROD.CP_PASSO_NOM
				,DIMTOLPA1		  = CADPROD.CP_PASSO_NOM_VAR1
				,DIMTOLPAS		  = CADPROD.CP_PASSO_NOM_VAR2
				,SAPCOR01		  = CADPROD.CP_COR_IMPRES1
				,SAPCOR02		  = CADPROD.CP_COR_IMPRES2
				,SAPCOR03		  = CADPROD.CP_COR_IMPRES3
				,SAPCOR04		  = CADPROD.CP_COR_IMPRES4
				,SAPCOR05		  = CADPROD.CP_COR_IMPRES5
				,SAPCOR06		  = CADPROD.CP_COR_IMPRES6
				,SAPCOR07		  = CADPROD.CP_COR_IMPRES7
				,SAPCOR08		  = CADPROD.CP_COR_IMPRES8
				,SAPCOR09		  = CADPROD.CP_COR_IMPRES9
				,SAPCOR10		  = CADPROD.CP_COR_IMPRES10
				,ALTFOTO		  = CADPROD.CP_FOTOC_ALTURA1
				,ALTFOTO1		  = CADPROD.CP_FOTOC_ALTURA2
				,ALTFOTO2		  = CADPROD.CP_FOTOC_ALTURA3
			    ,ALTFOTO3		  = CADPROD.CP_FOTOC_ALTURA4
				,LARGFOTO		  = CADPROD.CP_DA_FO_LAR1
				,LARGFOTO1		  = CADPROD.CP_DA_FO_LAR2
				,LARGFOTO2		  = CADPROD.CP_DA_FO_LAR3
			    ,LARGFOTO3		  = CADPROD.CP_DA_FO_LAR4
				,CORFOTO		  = CADPROD.CP_FOTOC_COR
				,CORFOTO1		  = CADPROD.CP_FOTOC_COR2
				,CORFOTO2		  = CADPROD.CP_FOTOC_COR3
			    ,CORFOTO3		  = CADPROD.CP_FOTOC_COR4
				,DIMPLVCHV		  = CADPROD.CP_CHAVE_PAL2
			    ,SAPPLVCHI		  = CADPROD.CP_FOTOC_PALAVRA_CHAVE
				,DIMSENEMB		  = CADPROD.CP_EMBOBI
			    ,SAPSENEMBI		  = CADPROD.CP_DE_EM_SEN2
				,DIMNUMEME		  = CADPROD.CP_EMENDA_NUMMAX
				,SAPTIPEME		  = TIPO_EMENDA.DESCRICAO
				,SAPCOREME		  = COR_EMENDA.DESCRICAO
				,DIMMATEME		  = MATERIAL_EMENDA.DESCRICAO
				,DIMESPEMB		  = CADPROD.CP_ESPEC_EMBA
				,LARGURA3		  = CADPROD.CP_CAMPO_GRAV
				,SAPTIPFILM		  = TIPO_FILME.DESCRICAO
				,SAPTIPCORT		  = TIPO_CORTE.DESCRICAO
				,SAPTIPTRAT		  = TIPO_TRATAMENTO.DESCRICAO
				,DIMGRAUDI		  = CADPROD.CP_GRAU_TRATAM
				,DIMGRAUD1		  = CADPROD.CP_GRAU_TRATAM_MAIOR
				,DIMGRAUD2		  = CADPROD.CP_GRAU_TRATAM_MENOR
				,SAPLADTRAT		  = LADO_TRATADO.DESCRICAO
				,SAPFAXTRAT		  = FAIXAS_SEM_TRATAMENTO.DESCRICAO
				,SAPTIPTUB		  = TIPO_TUBO.DESCRICAO
				,DIMDIATUB		  = CADPROD.CP_TUBO_DIAM
				,SAPCODPROCLI	  = CADPROD.COD_PRODCLI
				,CIRCUNFERENCIA	  = CADPROD.CP_CIRCUNF_CILINDRO
				,DIMDIACIL		  = CADPROD.CP_DIAM_CILINDRO
				,DIMQTDOPE		  = CADPROD.CP_DE_OP_QUA2
				,SAPPRIRETIC01	  = CADPROD.CP_COR_1_RET1
				,SAPPRIRETIC02	  = CADPROD.CP_COR_2_RET1
				,SAPPRIRETIC03	  = CADPROD.CP_COR_3_RET1
				,SAPPRIRETIC04	  = CADPROD.CP_COR_4_RET1
				,SAPPRIRETIC05	  = CADPROD.CP_COR_5_RET1
				,SAPPRIRETIC06	  = CADPROD.CP_COR_6_RET1
				,SAPPRIRETIC07	  = CADPROD.CP_COR_7_RET1
				,SAPPRIRETIC08	  = CADPROD.CP_COR_8_RET1
				,SAPPRIRETIC09	  = CADPROD.CP_COR_9_RET1
				,SAPPRIRETIC10	  = CADPROD.CP_COR_10_RET1
				,SAPSEGRETIC01    = CADPROD.CP_RETIC_SEG2_COR1
				,SAPSEGRETIC02    = CADPROD.CP_RETIC_SEG2_COR2
				,SAPSEGRETIC03    = CADPROD.CP_RETIC_SEG2_COR3
				,SAPSEGRETIC04    = CADPROD.CP_RETIC_SEG2_COR4
				,SAPSEGRETIC05    = CADPROD.CP_RETIC_SEG2_COR5
				,SAPSEGRETIC06    = CADPROD.CP_RETIC_SEG2_COR6
				,SAPSEGRETIC07    = CADPROD.CP_RETIC_SEG2_COR7
				,SAPSEGRETIC08    = CADPROD.CP_RETIC_SEG2_COR8
				,SAPSEGRETIC09    = CADPROD.CP_RETIC_SEG2_COR9
				,SAPSEGRETIC10    = CADPROD.CP_RETIC_SEG2_COR10
				,SAPANILOX01	  = CADPROD.CP_COR1_ANI2
				,SAPANILOX02	  = CADPROD.CP_COR2_ANI2
				,SAPANILOX03	  = CADPROD.CP_COR3_ANI2
				,SAPANILOX04	  = CADPROD.CP_COR4_ANI2
				,SAPANILOX05	  = CADPROD.CP_COR5_ANI2
				,SAPANILOX06	  = CADPROD.CP_COR6_ANI2
				,SAPANILOX07	  = CADPROD.CP_COR7_ANI2
				,SAPANILOX08	  = CADPROD.CP_COR8_ANI2
				,SAPANILOX09	  = CADPROD.CP_COR9_ANI2
				,SAPANILOX10	  = CADPROD.CP_COR10_ANI2
				,SAPFITA01		  = CADPROD.CP_FITA_COD2_COR1
				,SAPFITA02		  = CADPROD.CP_FITA_COD2_COR2
				,SAPFITA03        = CADPROD.CP_FITA_COD2_COR3
				,SAPFITA04        = CADPROD.CP_FITA_COD2_COR4
				,SAPFITA05        = CADPROD.CP_FITA_COD2_COR5
				,SAPFITA06        = CADPROD.CP_FITA_COD2_COR6
				,SAPFITA07        = CADPROD.CP_FITA_COD2_COR7
				,SAPFITA08        = CADPROD.CP_FITA_COD2_COR8
				,SAPFITA09        = CADPROD.CP_FITA_COD2_COR9
				,SAPFITA10        = CADPROD.CP_FITA_COD2_COR10    
				,SAPLINEATUR01	  = CADPROD.CP_LINEATURA1
				,SAPLINEATUR02	  = CADPROD.CP_LINEATURA2
				,SAPLINEATUR03	  = CADPROD.CP_LINEATURA3
				,SAPLINEATUR04	  = CADPROD.CP_LINEATURA4
				,SAPLINEATUR05	  = CADPROD.CP_LINEATURA5
				,SAPLINEATUR06	  = CADPROD.CP_LINEATURA6
				,SAPLINEATUR07	  = CADPROD.CP_LINEATURA7
				,SAPLINEATUR08	  = CADPROD.CP_LINEATURA8
				,SAPLINEATUR09	  = CADPROD.CP_LINEATURA9
				,SAPLINEATUR10	  = CADPROD.CP_LINEATURA10
				,SAPFOTOPOL01	  = CADPROD.CP_FOTOPOLIMERO1
				,SAPFOTOPOL02	  = CADPROD.CP_FOTOPOLIMERO2
				,SAPFOTOPOL03	  = CADPROD.CP_FOTOPOLIMERO3
				,SAPFOTOPOL04	  = CADPROD.CP_FOTOPOLIMERO4
				,SAPFOTOPOL05	  = CADPROD.CP_FOTOPOLIMERO5
				,SAPFOTOPOL06	  = CADPROD.CP_FOTOPOLIMERO6
				,SAPFOTOPOL07	  = CADPROD.CP_FOTOPOLIMERO7
				,SAPFOTOPOL08	  = CADPROD.CP_FOTOPOLIMERO8
				,SAPFOTOPOL09	  = CADPROD.CP_FOTOPOLIMERO9
				,SAPFOTOPOL10	  = CADPROD.CP_FOTOPOLIMERO10
				,SAPNVCODARTE	  = CADPROD.CP_GERA_NOVO_ARTE
				,DIMCODART		  = CADPROD.CP_COD_ARTE
				,CODIGOBARRAS	  = CADPROD.CP_COD_BARRAS_CLI
				,SAPMOTVER		  = CADPROD.MOTIVO
				,ALTTEC			  = CADPROD.CP_PASSO_MONTAG
				,DIMLADIMP		  = SUBSTRING(LADO_IMPRESSO.DESCRICAO, 1,1) -- Atualizar somente a inicial do campo
				,SAPCODPROCLI     = CADPROD.CP_COD_CLI
				,SAPCLIENTE		  = CADPROD.CP_DESC_CLI
				,SAPPRODIMP 	  = TIPO_IMPRESSAO.DESCRICAO 
				--     SYSPROD_PROGRESS.DBO.PROGRESS_SAPPRODUT é uma view  
			FROM SYSPROD_PROGRESS.DBO.PROGRESS_SAPPRODUT AS PROGRESS_PRODUTOS  
			LEFT JOIN CADPROD AS CADPROD
			ON PROGRESS_PRODUTOS.SAPCODEMP = ID_EMP AND PROGRESS_PRODUTOS.SAPCODPRO COLLATE SQL_Latin1_General_CP1_CI_AS = CODPROD COLLATE SQL_Latin1_General_CP1_CI_AS
			LEFT JOIN PROGRESSTST.BDGERAL.PUB.TABCODSAP AS PROGRESS_DEPARA 
			ON CADPROD.ID_EMP = PROGRESS_DEPARA."SAP-CODEMP"
			LEFT JOIN TB_COR_EMENDA AS COR_EMENDA
            ON COR_EMENDA.ID = CADPROD.CP_EMENDA_COR
            LEFT JOIN TB_MATERIAL_EMENDA AS MATERIAL_EMENDA
            ON MATERIAL_EMENDA.ID = CADPROD.CP_EMENDA_MATE
            LEFT JOIN TB_TIPO_FILME AS TIPO_FILME
            ON TIPO_FILME.ID = CADPROD.CP_TIPO_FILME
            LEFT JOIN TB_TIPO_CORTE AS TIPO_CORTE
            ON TIPO_CORTE.ID = CADPROD.CP_TIPO_CORTE
            LEFT JOIN TB_TIPO_TRATAMENTO AS TIPO_TRATAMENTO
            ON TIPO_TRATAMENTO.ID = CADPROD.CP_TIPO_TRATAM
            LEFT JOIN TB_LADO_TRATADO AS LADO_TRATADO
            ON LADO_TRATADO.ID = CADPROD.CP_LADO_TRATADO
            LEFT JOIN TB_FAIXAS_SEM_TRATAMENTO AS FAIXAS_SEM_TRATAMENTO
            ON FAIXAS_SEM_TRATAMENTO.ID = CADPROD.CP_FAIXAS_SEM_TRATAM
            LEFT JOIN TB_TIPO_TUBO AS TIPO_TUBO
            ON TIPO_TUBO.ID = CADPROD.CP_TUBO_TIPO
            LEFT JOIN TB_TIPO_SACO AS TIPO_SACO
            ON TIPO_SACO.ID = CADPROD.CP_SACO_TIPO
            LEFT JOIN TB_LADO_IMPRESSO AS LADO_IMPRESSO
            ON LADO_IMPRESSO.ID = CADPROD.CP_LADO_IMPRES
            LEFT JOIN TB_TIPO_EMENDA AS TIPO_EMENDA
            ON TIPO_EMENDA.ID = CADPROD.CP_EMENDA_DESCR
            LEFT JOIN TB_POSICAO_NA_CAIXA AS POSICAO_NA_CAIXA
            ON POSICAO_NA_CAIXA.ID = CADPROD.CP_POSICAO_CAIXA
            LEFT JOIN TB_FACE_LAMINACAO AS FACE_LAMINACAO
            ON FACE_LAMINACAO.ID = CADPROD.CP_FACE_LAMIN
			LEFT JOIN TB_TIPO_IMPRESSAO AS TIPO_IMPRESSAO
			ON TIPO_IMPRESSAO.ID = CADPROD.CP_PROD_IMPRES
			LEFT JOIN UNIDADES AS UNIDADES
			ON UNIDADES.ID_UNID = CADPROD.ID_UNID AND CADPROD.ID_EMP = UNIDADES.ID_EMP
			WHERE PROGRESS_PRODUTOS.SAPCODEMP = @ID_EMP AND PROGRESS_PRODUTOS.SAPCODPRO = @CODPROD
		END
		ELSE
		--Senao insira os dados na tabela do PROGRESS
		BEGIN 
			--     SYSPROD_PROGRESS.DBO.PROGRESS_SAPPRODUT é uma view 
			INSERT INTO SYSPROD_PROGRESS.DBO.PROGRESS_SAPPRODUT   ( EMPCODEMP       
																   ,SAPCODEMP       
																   ,SAPCODPRO       
																   ,SAPDESCRI       
																   ,PRODATCAD       
																   ,SAPCODVID		 
																   ,TUNSIGUNI	
																   ,DIMCODSIF		 
																   ,DIMLGCORT       
																   ,DIMTLCORT		 
																   ,DIMTLCOR1		 
																   ,DIMLGLONG		 
																   ,DIMLGTRAN		 
																   ,DIMDIAINT		 
																   ,DIMDMEXTE		 
																   ,DIMDENSID		 
																   ,DIMESPESS		 
																   ,DIMESTOT1		 
																   ,DIMESTOT2		 
																   ,DIMGRTOTA		 
																   ,DIMTOLGM2		 
																   ,DIMTOLEGM		 
																   ,DIMGRMTLI		 
																   ,DIMGRMTL1		 
																   ,DIMGRMTL2		 
																   ,DIMREPLAT		 
																   ,DIMREPLON		 
																   ,PROSELFSC		 
																   ,PROSEPEFC		 
																   ,DIMBASPAL		 
																   ,DIMQTITCX		 
																   ,DIMBOBKGS		 
																   ,DIMMTSBOB		 
																   ,DIMCPRSAC		 
																   ,DIMVARALT		 
																   ,DIMLGRSAC		 
																   ,DIMVARLGS		 
																   ,SAPNVCODFOTO	 
																   ,SAPSEQFOTO		 
																   ,DIMFMVARIMG	 
																   ,SAPNVCODPADCOR	 
																   ,SAPSEQPAD		 
																   ,DIMPASSFC		 
																   ,DIMTOLPA1		 
																   ,DIMTOLPAS		 
																   ,SAPCOR01		 
																   ,SAPCOR02		 
																   ,SAPCOR03		 
																   ,SAPCOR04		 
																   ,SAPCOR05		 
																   ,SAPCOR06		 
																   ,SAPCOR07		 
																   ,SAPCOR08		 
																   ,SAPCOR09		 
																   ,SAPCOR10		 
																   ,ALTFOTO		 
																   ,ALTFOTO1		 
																   ,ALTFOTO2		 
																   ,ALTFOTO3		 
																   ,LARGFOTO		 
																   ,LARGFOTO1		 
																   ,LARGFOTO2		 
																   ,LARGFOTO3		 
																   ,CORFOTO		 
																   ,CORFOTO1		 
																   ,CORFOTO2		 
																   ,CORFOTO3		 
																   ,DIMPLVCHV		 
																   ,SAPPLVCHI		 
																   ,DIMSENEMB		 
																   ,SAPSENEMBI		 
																   ,DIMNUMEME		 
																   ,SAPTIPEME		 
																   ,SAPCOREME		 
																   ,DIMMATEME		 
																   ,DIMESPEMB		 
																   ,LARGURA3		 
																   ,SAPTIPFILM		 
																   ,SAPTIPCORT		 
																   ,SAPTIPTRAT		 
																   ,DIMGRAUDI		 
																   ,DIMGRAUD1		 
																   ,DIMGRAUD2		 
																   ,SAPLADTRAT		 
																   ,SAPFAXTRAT		 
																   ,SAPTIPTUB		 
																   ,DIMDIATUB		 
																   ,SAPCODPROCLI	 
																   ,CIRCUNFERENCIA	 
																   ,DIMDIACIL		 
																   ,DIMQTDOPE		 
																   ,SAPPRIRETIC01	 
																   ,SAPPRIRETIC02	 
																   ,SAPPRIRETIC03	 
																   ,SAPPRIRETIC04	 
																   ,SAPPRIRETIC05	 
																   ,SAPPRIRETIC06	 
																   ,SAPPRIRETIC07	 
																   ,SAPPRIRETIC08	 
																   ,SAPPRIRETIC09	 
																   ,SAPPRIRETIC10	 
																   ,SAPSEGRETIC01   
																   ,SAPSEGRETIC02   
																   ,SAPSEGRETIC03   
																   ,SAPSEGRETIC04   
																   ,SAPSEGRETIC05   
																   ,SAPSEGRETIC06   
																   ,SAPSEGRETIC07   
																   ,SAPSEGRETIC08   
																   ,SAPSEGRETIC09   
																   ,SAPSEGRETIC10   
																   ,SAPANILOX01	 
																   ,SAPANILOX02	 
																   ,SAPANILOX03	 
																   ,SAPANILOX04	 
																   ,SAPANILOX05	 
																   ,SAPANILOX06	 
																   ,SAPANILOX07	 
																   ,SAPANILOX08	 
																   ,SAPANILOX09	 
																   ,SAPANILOX10	 
																   ,SAPFITA01		 
																   ,SAPFITA02		 
																   ,SAPFITA03       
																   ,SAPFITA04       
																   ,SAPFITA05       
																   ,SAPFITA06       
																   ,SAPFITA07       
																   ,SAPFITA08       
																   ,SAPFITA09       
																   ,SAPFITA10       
																   ,SAPLINEATUR01	 
																   ,SAPLINEATUR02	 
																   ,SAPLINEATUR03	 
																   ,SAPLINEATUR04	 
																   ,SAPLINEATUR05	 
																   ,SAPLINEATUR06	 
																   ,SAPLINEATUR07	 
																   ,SAPLINEATUR08	 
																   ,SAPLINEATUR09	 
																   ,SAPLINEATUR10	 
																   ,SAPFOTOPOL01	 
																   ,SAPFOTOPOL02	 
																   ,SAPFOTOPOL03	 
																   ,SAPFOTOPOL04	 
																   ,SAPFOTOPOL05	 
																   ,SAPFOTOPOL06	 
																   ,SAPFOTOPOL07	 
																   ,SAPFOTOPOL08	 
																   ,SAPFOTOPOL09	 
																   ,SAPFOTOPOL10	 
																   ,SAPNVCODARTE	 
																   ,DIMCODART		 
																   ,CODIGOBARRAS	 
																   ,SAPMOTVER		 
																   ,ALTTEC			 
																   ,DIMLADIMP		 
																   ,SAPCODPROCLI    
																   ,SAPCLIENTE		
																   ,SAPPRODIMP
																	)
			SELECT PROGRESS_DEPARA."EMP-CODEMP"
				   ,CADPROD.ID_EMP                                                            
				   ,CADPROD.CODPROD                                                           
				   ,CADPROD.DESCPROD                                                          
				   ,CADPROD.DATA_CAD_MATER  
				   ,CADPROD.COD_VIDA
				   ,UNIDADES.SIMBOL
				   ,CADPROD.COD_SIF
				   ,CADPROD.CP_LARG
				   ,CADPROD.CP_LARG_NOM_MAIOR
				   ,CADPROD.CP_LARG_NOM_MENOR
				   ,CADPROD.CP_LARG_LONG_NOM
				   ,CADPROD.CP_LARG_TRANS_NOM
				   ,CADPROD.CP_DIAM_INTERNO
				   ,CADPROD.CP_DIAM_EXTERNO
				   ,CADPROD.CP_DENSIDADE
				   ,CADPROD.CP_ESPE
				   ,CADPROD.CP_ESPESSURA_MAIOR
				   ,CADPROD.CP_ESPESSURA_MENOR
				   ,CADPROD.CP_GRAM_TOTAL
				   ,CADPROD.CP_GRAM_TOTAL_MIN
				   ,CADPROD.CP_GRAM_TOTAL_MAX
				   ,CADPROD.CP_MASSA_ML
				   ,CADPROD.CP_MASSA_ML_MAIOR
				   ,CADPROD.CP_MASSA_ML_MENOR
				   ,CADPROD.CP_REPETICOES
				   ,CADPROD.CPV_REP_ALT
				   ,CADPROD.CP_SELO_FSC
				   ,CADPROD.CP_SELO_PEFC
				   ,CADPROD.CP_VOLUMES_PALLET
				   ,CADPROD.CP_PECAS_VOLUME
				   ,CADPROD.CP_KILOS_BOBINA
				   ,CADPROD.CP_METROS_POR_BOBINA
				   ,CADPROD.CP_SACO_ALT
				   ,CADPROD.CP_SACO_ALT_VAR1
				   ,CADPROD.CP_SACO_LARG
				   ,CADPROD.CP_SACO_LARG_VAR1
				   ,CADPROD.CP_GERA_COD_FOTOMONTAGEM
				   ,CADPROD.CP_FOTOMONTAGEM
				   ,CADPROD.CP_FOTOM_VAR_LAYOUT
				   ,CADPROD.CP_GERA_COD_PAD_COR
				   ,CADPROD.CP_PADRAO_COR
				   ,CADPROD.CP_PASSO_NOM
				   ,CADPROD.CP_PASSO_NOM_VAR1
				   ,CADPROD.CP_PASSO_NOM_VAR2
				   ,CADPROD.CP_COR_IMPRES1
				   ,CADPROD.CP_COR_IMPRES2
				   ,CADPROD.CP_COR_IMPRES3
				   ,CADPROD.CP_COR_IMPRES4
				   ,CADPROD.CP_COR_IMPRES5
				   ,CADPROD.CP_COR_IMPRES6
				   ,CADPROD.CP_COR_IMPRES7
				   ,CADPROD.CP_COR_IMPRES8
				   ,CADPROD.CP_COR_IMPRES9
				   ,CADPROD.CP_COR_IMPRES10
				   ,CADPROD.CP_FOTOC_ALTURA1
				   ,CADPROD.CP_FOTOC_ALTURA2
				   ,CADPROD.CP_FOTOC_ALTURA3
				   ,CADPROD.CP_FOTOC_ALTURA4
				   ,CADPROD.CP_DA_FO_LAR1
				   ,CADPROD.CP_DA_FO_LAR2
				   ,CADPROD.CP_DA_FO_LAR3
				   ,CADPROD.CP_DA_FO_LAR4
				   ,CADPROD.CP_FOTOC_COR
				   ,CADPROD.CP_FOTOC_COR2
				   ,CADPROD.CP_FOTOC_COR3
				   ,CADPROD.CP_FOTOC_COR4
				   ,CADPROD.CP_CHAVE_PAL2
				   ,CADPROD.CP_FOTOC_PALAVRA_CHAVE
				   ,CADPROD.CP_EMBOBI
				   ,CADPROD.CP_DE_EM_SEN2
				   ,CADPROD.CP_EMENDA_NUMMAX
				   ,TIPO_EMENDA.DESCRICAO
				   ,COR_EMENDA.DESCRICAO
				   ,MATERIAL_EMENDA.DESCRICAO
				   ,CADPROD.CP_ESPEC_EMBA
				   ,CADPROD.CP_CAMPO_GRAV
				   ,TIPO_FILME.DESCRICAO
				   ,TIPO_CORTE.DESCRICAO
				   ,TIPO_TRATAMENTO.DESCRICAO
				   ,CADPROD.CP_GRAU_TRATAM
				   ,CADPROD.CP_GRAU_TRATAM_MAIOR
				   ,CADPROD.CP_GRAU_TRATAM_MENOR
				   ,LADO_TRATADO.DESCRICAO
				   ,FAIXAS_SEM_TRATAMENTO.DESCRICAO
				   ,TIPO_TUBO.DESCRICAO
				   ,CADPROD.CP_TUBO_DIAM
				   ,CADPROD.COD_PRODCLI
				   ,CADPROD.CP_CIRCUNF_CILINDRO
				   ,CADPROD.CP_DIAM_CILINDRO
				   ,CADPROD.CP_DE_OP_QUA2
				   ,CADPROD.CP_COR_1_RET1
				   ,CADPROD.CP_COR_2_RET1
				   ,CADPROD.CP_COR_3_RET1
				   ,CADPROD.CP_COR_4_RET1
				   ,CADPROD.CP_COR_5_RET1
				   ,CADPROD.CP_COR_6_RET1
				   ,CADPROD.CP_COR_7_RET1
				   ,CADPROD.CP_COR_8_RET1
				   ,CADPROD.CP_COR_9_RET1
				   ,CADPROD.CP_COR_10_RET1
				   ,CADPROD.CP_RETIC_SEG2_COR1
				   ,CADPROD.CP_RETIC_SEG2_COR2
				   ,CADPROD.CP_RETIC_SEG2_COR3
				   ,CADPROD.CP_RETIC_SEG2_COR4
				   ,CADPROD.CP_RETIC_SEG2_COR5
				   ,CADPROD.CP_RETIC_SEG2_COR6
				   ,CADPROD.CP_RETIC_SEG2_COR7
				   ,CADPROD.CP_RETIC_SEG2_COR8
				   ,CADPROD.CP_RETIC_SEG2_COR9
				   ,CADPROD.CP_RETIC_SEG2_COR10
				   ,CADPROD.CP_COR1_ANI2
				   ,CADPROD.CP_COR2_ANI2
				   ,CADPROD.CP_COR3_ANI2
				   ,CADPROD.CP_COR4_ANI2
				   ,CADPROD.CP_COR5_ANI2
				   ,CADPROD.CP_COR6_ANI2
				   ,CADPROD.CP_COR7_ANI2
				   ,CADPROD.CP_COR8_ANI2
				   ,CADPROD.CP_COR9_ANI2
				   ,CADPROD.CP_COR10_ANI2
				   ,CADPROD.CP_FITA_COD2_COR1
				   ,CADPROD.CP_FITA_COD2_COR2
				   ,CADPROD.CP_FITA_COD2_COR3
				   ,CADPROD.CP_FITA_COD2_COR4
				   ,CADPROD.CP_FITA_COD2_COR5
				   ,CADPROD.CP_FITA_COD2_COR6
				   ,CADPROD.CP_FITA_COD2_COR7
				   ,CADPROD.CP_FITA_COD2_COR8
				   ,CADPROD.CP_FITA_COD2_COR9
				   ,CADPROD.CP_FITA_COD2_COR10       
				   ,CADPROD.CP_LINEATURA1
				   ,CADPROD.CP_LINEATURA2
				   ,CADPROD.CP_LINEATURA3
				   ,CADPROD.CP_LINEATURA4
				   ,CADPROD.CP_LINEATURA5
				   ,CADPROD.CP_LINEATURA6
				   ,CADPROD.CP_LINEATURA7
				   ,CADPROD.CP_LINEATURA8
				   ,CADPROD.CP_LINEATURA9
				   ,CADPROD.CP_LINEATURA10
				   ,CADPROD.CP_FOTOPOLIMERO1
				   ,CADPROD.CP_FOTOPOLIMERO2
				   ,CADPROD.CP_FOTOPOLIMERO3
				   ,CADPROD.CP_FOTOPOLIMERO4
				   ,CADPROD.CP_FOTOPOLIMERO5
				   ,CADPROD.CP_FOTOPOLIMERO6
				   ,CADPROD.CP_FOTOPOLIMERO7
				   ,CADPROD.CP_FOTOPOLIMERO8
				   ,CADPROD.CP_FOTOPOLIMERO9
				   ,CADPROD.CP_FOTOPOLIMERO10
				   ,CADPROD.CP_GERA_NOVO_ARTE
				   ,CADPROD.CP_COD_ARTE
				   ,CADPROD.CP_COD_BARRAS_CLI
				   ,CADPROD.MOTIVO
				   ,CADPROD.CP_PASSO_MONTAG
				   ,SUBSTRING(LADO_IMPRESSO.DESCRICAO, 1,1) -- inserir somente a inicial do campo
				   ,CADPROD.CP_COD_CLI
				   ,CADPROD.CP_DESC_CLI
				   ,TIPO_IMPRESSAO.DESCRICAO 
			FROM CADPROD AS CADPROD
			LEFT JOIN PROGRESSTST.BDGERAL.PUB.TABCODSAP AS PROGRESS_DEPARA 
			ON CADPROD.ID_EMP = PROGRESS_DEPARA."SAP-CODEMP"
			LEFT JOIN TB_COR_EMENDA AS COR_EMENDA
            ON COR_EMENDA.ID = CADPROD.CP_EMENDA_COR
            LEFT JOIN TB_MATERIAL_EMENDA AS MATERIAL_EMENDA
            ON MATERIAL_EMENDA.ID = CADPROD.CP_EMENDA_MATE
            LEFT JOIN TB_TIPO_FILME AS TIPO_FILME
            ON TIPO_FILME.ID = CADPROD.CP_TIPO_FILME
            LEFT JOIN TB_TIPO_CORTE AS TIPO_CORTE
            ON TIPO_CORTE.ID = CADPROD.CP_TIPO_CORTE
            LEFT JOIN TB_TIPO_TRATAMENTO AS TIPO_TRATAMENTO
            ON TIPO_TRATAMENTO.ID = CADPROD.CP_TIPO_TRATAM
            LEFT JOIN TB_LADO_TRATADO AS LADO_TRATADO
            ON LADO_TRATADO.ID = CADPROD.CP_LADO_TRATADO
            LEFT JOIN TB_FAIXAS_SEM_TRATAMENTO AS FAIXAS_SEM_TRATAMENTO
            ON FAIXAS_SEM_TRATAMENTO.ID = CADPROD.CP_FAIXAS_SEM_TRATAM
            LEFT JOIN TB_TIPO_TUBO AS TIPO_TUBO
            ON TIPO_TUBO.ID = CADPROD.CP_TUBO_TIPO
            LEFT JOIN TB_TIPO_SACO AS TIPO_SACO
            ON TIPO_SACO.ID = CADPROD.CP_SACO_TIPO
            LEFT JOIN TB_LADO_IMPRESSO AS LADO_IMPRESSO
            ON LADO_IMPRESSO.ID = CADPROD.CP_LADO_IMPRES
            LEFT JOIN TB_TIPO_EMENDA AS TIPO_EMENDA
            ON TIPO_EMENDA.ID = CADPROD.CP_EMENDA_DESCR
            LEFT JOIN TB_POSICAO_NA_CAIXA AS POSICAO_NA_CAIXA
            ON POSICAO_NA_CAIXA.ID = CADPROD.CP_POSICAO_CAIXA
            LEFT JOIN TB_FACE_LAMINACAO AS FACE_LAMINACAO
            ON FACE_LAMINACAO.ID = CADPROD.CP_FACE_LAMIN
			LEFT JOIN TB_TIPO_IMPRESSAO AS TIPO_IMPRESSAO
			ON TIPO_IMPRESSAO.ID = CADPROD.CP_PROD_IMPRES
			LEFT JOIN UNIDADES AS UNIDADES
			ON UNIDADES.ID_UNID = CADPROD.ID_UNID AND CADPROD.ID_EMP = UNIDADES.ID_EMP
			WHERE CADPROD.ID_EMP = @ID_EMP AND CADPROD.CODPROD = @CODPROD
			
			--Atualize o campo INTEGRADO_PROGRESS = 1 onde ID_EMP = @ID_EMP e CODPROD = @CODPROD para constar que o produto já foi integrado no PROGRESS
			-- Se o mesmo existir no Progress
			IF EXISTS(SELECT FROM SYSPROD_PROGRESS.DBO.PROGRESS_SAPPRODUT
						where SAPCODEMP = @ID_EMP and SAP.SAPCODPRO = @CADPROD
			)
			BEGIN
				UPDATE CADPROD
				SET INTEGRADO_PROGRESS = 1
				WHERE ID_EMP = @ID_EMP AND CODPROD = @CODPROD
			END
		END
	END
	END TRY
	BEGIN CATCH
		/*retorna a mensage quando houver erro na integracao*/
	select @ReturnMessage = 'Error Number ' + cast(ERROR_NUMBER() as varchar(max)) +
							', Error Severity '  + cast(ERROR_SEVERITY() as varchar(max)) +
							', Error State ' + cast(ERROR_STATE() as varchar(max)) + 
							', ErrorProcedure ' + ERROR_PROCEDURE() +
							', ErrorLine ' + cast(ERROR_LINE() as varchar(max)) +
							', ErrorMessage ' + ERROR_MESSAGE();
	END CATCH
END